version: '3.9'
services:
  postgres:
    image: postgres:16-alpine
    container_name: parking-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: parking_lot_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: parking-backend
    depends_on:
      - postgres
    environment:
      NODE_ENV: production
      PORT: 3000
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: root
      DB_NAME: parking_lot_dev
      JWT_SECRET: parking-lot-docker-jwt-secret-32-characters
      JWT_EXPIRES_IN: 28800
      PARKING_GRACE_PERIOD_MINUTES: 15
      PARKING_RATE_CAR: 40
      PARKING_RATE_BIKE: 20
      PARKING_RATE_TRUCK: 80
    ports:
      - '3000:3000'

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: parking-frontend
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3000/api/v1
      NEXT_PUBLIC_WS_URL: http://localhost:3000/parking
    ports:
      - '3001:3001'

volumes:
  pgdata:
